services:
  - type: web
    name: chaterp-database
    plan: free
    runtime: docker
    image:
      url: etiennepaquet85/chaterp-persistence:latest
    envVars:
      - key: PORT
        value: "80"
