services:
  - type: web
    name: chaterp-database
    plan: free
    runtime: docker
    dockerfilePath: ./database/Dockerfile
    envVars:
      - key: PORT
        value: "80"

  - type: web
    name: chaterp-backend
    plan: free
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_API_URL
        value: "https://chaterp-database.onrender.com"
      - key: ASPNETCORE_PORT
        value: "80"

  - type: web
    name: chaterp-frontend
    plan: free
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: "https://chaterp-backend.onrender.com"
