name: Bug Report
description: Signaler un bug dans ChatERP
title: "[BUG] "
labels: [bug]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Décris clairement le bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      placeholder: |
        1. Aller à ‘...’
        2. Faire ‘...’
        3. Observer ‘...’
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: (Optionnel) Tag ou commit concerné
