name: Bug Report
description: Report a new bug in ChatERP
title: "CHRP-<id> : <Summary>"
labels: [bug]

body:

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the new bug in detail.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What do you expect to happen instead?
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide the steps to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Do '...'
        3. Observe '...'
    validations:
      required: true

  - type: file
    id: attachments
    attributes:
      label: Attachments (optional)
      description: Upload screenshots, logs, or other files to help diagnose the bug.
    validations:
      required: false
