name: Bug Report
description: Report a new bug in ChatERP
title: "CHRP-<id> : <Summary>"
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        **Issue Type:** Bug

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the new bug in detail.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What do you expect to happen instead?
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide the steps to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Do '...'
        3. Observe '...'
    validations:
      required: true

  - type: textarea
    id: attachments_info
    attributes:
      label: Attachments (optional)
      description: Please attach screenshots, logs, or other files using GitHub’s "Attach files" feature below the comment box.
    validations:
      required: false
