name: Feature Request
description: Proposer une amélioration ou fonctionnalité
title: "[FEATURE] "
labels: [enhancement]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Décris la fonctionnalité souhaitée.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Objectif
      description: Pourquoi est-ce utile ?
