name: Feature Request
description: Propose a new feature for ChatERP
title: "CHRP-<id> : <Summary>"
labels: [feature]

body:
  - type: markdown
    attributes:
      value: |
        **Issue Type:** Feature

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the new feature in detail.
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: Why is this feature useful?
    validations:
      required: true

  - type: textarea
    id: steps_to_create
    attributes:
      label: Steps to Create
      description: Provide the steps to create the feature.
      placeholder: |
        1. Analyze '...'
        2. Implement '...'
        3. Test '...'
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria (optional)
      description: What conditions must be met for this request to be considered complete?
      placeholder: |
        - The feature is easily testable
        - The feature handles errors gracefully
        - The feature is user-friendly and intuitive
    validations:
      required: false
